### PR TITLE
Include types in npm package, enable module import

### PR DESCRIPTION
**Pull request by kaytwo**
I wanted to be able to `import { render } from 'webtreemap-cdt'` so I went down the rabbit hole of getting that to work. Since the CLI was broken I removed that code from this branch, and kept the `webtreemap.js` IIFE rollup build for backwards compatibility.

Feel free to edit/cherry pick this branch or not, internally we'll be using this new version via `@kaytwo/webtreemap-cdt` if the PR isn't merged.

### CODE REVIEW

**Comment by paulirish** [comment]
nice work over here btw :)

i'll probably keep CLI, though I know the commander types are a pain.  hopefully your other work here will pave the way.

thanks and yeah i'll cherrypick this stuff.

**Review by paulirish — APPROVED** [review]
I have followups to land (fixing the CLI) but i'll land this in one go.

**Comment by paulirish** [comment]
Thanks again @kaytwo. :)

**Comment by kaytwo** [comment]
My pleasure glad to see it merged, and thank you for your work on this package

**Pull request merged**
